name: Update Fun Fact

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual run from the Actions tab
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Fun Fact
        id: funfact
        run: |
          RESPONSE=$(curl -s "https://uselessfacts.jsph.pl/api/v2/facts/random?language=en")
          FACT=$(echo "$RESPONSE" | jq -r .text)
          echo "Response: $RESPONSE"  # Debugging line
          echo "Fact: $FACT"  # Debugging line
          if [ -z "$FACT" ] || [ "$FACT" == "null" ]; then
            echo "Error: Unable to fetch fun fact"
            exit 1
          fi
          echo "::set-output name=fact::$FACT"
      - name: Update README
        run: |
          FACT="${{ steps.funfact.outputs.fact }}"
          echo "$FACT"
          # Replace the fun fact content after the marker in README.md
          sed -i "/<!-- FUNFACT -->/s/.*/⚡ Fun fact: $FACT/" README.md

      - name: Commit and Push
        run: |
          git config --local user.email "jyothishram.jn@gmail.com"
          git config --local user.name "jyothish-ram"
          git add README.md
          git commit -m "Update README with new fun fact"
          git push
