name: Update Fun Fact

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Fun Fact
        id: funfact
        run: |
          RESPONSE=$(curl -s "https://uselessfacts.jsph.pl/api/v2/facts/random?language=en")
          FACT=$(echo "$RESPONSE" | jq -r .text)
          echo "Response: $RESPONSE"  # Debugging line
          echo "Fact: $FACT"  # Debugging line
          if [ -z "$FACT" ] || [ "$FACT" == "null" ]; then
            echo "Error: Unable to fetch fun fact"
            exit 1
          fi
          echo "FACT='$FACT'" >> $GITHUB_ENV  # Setting output using Environment Files

      - name: Update README
        run: |
          FACT="${{ env.FACT }}"
          echo "$FACT"
          # Replace the fun fact in README.md
          sed -i "/<!-- FUNFACT -->/c\⚡ Fun fact: $FACT" README.md

      - name: Commit and Push
        run: |
          git config --local user.email "jyothishram.jn@gmail.com"
          git config --local user.name "jyothish-ram"
          git add README.md
          git commit -m "Update README with new fun fact"
          git push
