name: GitHub Profile Automation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours for Snake generation
    - cron: '0 0 * * *'  # Runs every day at midnight for Fun Fact update
  workflow_dispatch:  # Allows manual run from the Actions tab
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
    
      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Fun Fact
        id: funfact
        run: |
          RESPONSE=$(curl -s "https://uselessfacts.jsph.pl/api/v2/facts/random?language=en")
          FACT=$(echo "$RESPONSE" | jq -r .text)
          echo "Response: $RESPONSE"  # Debugging line
          echo "Fact: $FACT"  # Debugging line
          if [ -z "$FACT" ] || [ "$FACT" == "null" ]; then
            echo "Error: Unable to fetch fun fact"
            exit 1
          fi
          echo "::set-output name=fact::$FACT"

      - name: Update README
        run: |
          FACT="${{ steps.funfact.outputs.fact }}"
          echo "$FACT"
          # Replace the fun fact in README.md
          sed -i "/<!-- FUNFACT -->/c\⚡ Fun fact: $FACT" README.md

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with new fun fact"
          git push
